version: '3.8'

services:
  app:
    build: ./app
    image: app
    container_name: app-container
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app
    volumes:
      - wordpress-data:/var/www/ft_server/wordpress
      - phpmyadmin-data:/var/www/ft_server/phpmyadmin
      - nginx-config:/etc/nginx/sites-available
      - autoindex-bin:/usr/bin 
      - nginx-logs:/var/log/nginx

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'"]
      interval: 10s
      timeout: 10s
      retries: 12

  logstash:
    image: logstash:7.17.3
    container_name: logstash
    volumes:
      - ./services/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - nginx-logs:/var/log/nginx
    networks:
      - app
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - app
    volumes:
      - ./services/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./services/kibana/config/nginx-dashboard.ndjson:/usr/share/kibana/nginx-dashboard.ndjson
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q '\"state\":\"green\"'"]
      interval: 10s
      timeout: 10s
      retries: 12

  kibana-setup:
    image: alpine/curl
    container_name: kibana-setup
    networks:
      - app
    volumes:
      - ./services/kibana/config/setup-kibana.sh:/setup.sh
    command: ["sh", "/setup.sh"]
    depends_on:
      kibana:
        condition: service_healthy

networks:
  app:
    name: app

volumes:
  wordpress-data:
  phpmyadmin-data:
  nginx-config:
  autoindex-bin:
  nginx-logs:
  elasticsearch-data: