name: FT_Server CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        make build
        docker images

    - name: Run and test container
      run: |
        make run
        
        sleep 15
    
        echo "Testing WordPress..."
        curl -ski https://localhost:443/wordpress/ | grep -q "WordPress" || (echo "WordPress HTTPS check failed" && exit 1)

        echo "Testing phpMyAdmin..."
        curl -ski https://localhost:443/phpmyadmin/ | grep -q "phpMyAdmin" || (echo "phpMyAdmin check failed" && exit 1)

        echo "Checking container status..."
         docker ps --filter "name=ft_server_container" --format "{{.Status}}" | grep -q "Up" || (echo "Container is not running" && exit 1)

        echo "Container logs:"
        docker logs ft_server_container | tail -n 20    
    - name: Cleanup
      if: always()
      run: |
        make stop || true
        make fclean || true
