name: FT_Server CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        make build
        docker images

    - name: Run container with test
      run: |
        make run
        sleep 10  # Wait for services to start
        
        # Test HTTP services
        docker ps
        docker exec $(docker ps -q --filter "name=ft_server_container") curl -s http://localhost:80 | grep -q "WordPress" || (echo "WordPress test failed" && exit 1)
        docker exec $(docker ps -q --filter "name=ft_server_container") curl -s http://localhost:80/phpmyadmin | grep -q "phpMyAdmin" || (echo "phpMyAdmin test failed" && exit 1)

    - name: Cleanup
      if: always()
      run: |
        make stop
        make fclean
