name: FT_Server CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        make build
        docker images

    - name: Run and test container
      run: |
        # Use different ports to avoid conflicts
        docker run -d --rm --name ft_server_container \
          -p 8080:80 \
          -p 4443:443 \
          ft_server_image
        
        # Wait for services to start
        sleep 15
        
        # Test HTTP services
        curl -s http://localhost:8080 | grep -q "WordPress" || (echo "WordPress test failed" && exit 1)
        curl -s http://localhost:8080/phpmyadmin | grep -q "phpMyAdmin" || (echo "phpMyAdmin test failed" && exit 1)

    - name: Cleanup
      if: always()
      run: |
        docker stop ft_server_container || true
        docker rmi -f ft_server_image || true
