name: FT_Server CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        make build
        docker images

    - name: Run and test container
      run: |
        make run
        
        # Wait for services to start
        sleep 15
        
        # Test HTTP services
        curl -s http://localhost | grep -q "WordPress" || (echo "WordPress test failed" && exit 1)
        curl -s http://localhost/phpmyadmin | grep -q "phpMyAdmin" || (echo "phpMyAdmin test failed" && exit 1)

    - name: Cleanup
      if: always()
      run: |
        make stop || true
        make fclean || true
